Improve doc and fix legacy api
lyon-esport/TwitchPromExporter pull request #15
Opened 2021-03-24 21:01 UTC by M0NsTeRRR

2021-03-24 22:58 UTC, egguy commented on client.go
> +// GetFollows will get the number of followers for a user
Nice catch ;)

2021-03-24 23:00 UTC, egguy requested changes

2021-03-24 23:00 UTC, egguy commented on client.go
> -	CommunityIds []string  `json:"community_ids"`
Disappeared ?

2021-03-24 23:00 UTC, egguy commented on main.go
> +		if time.Now().After(twitch.Token.ExpiresDate.AddDate(0, 0, -10)) {
Why not using a percent remaining like 50% ? If twitch reduce to 24H the code will crash

2021-03-24 23:02 UTC, M0NsTeRRR commented on client.go
> -	CommunityIds []string  `json:"community_ids"`
Yes
https://dev.twitch.tv/docs/api/reference#get-streams

2021-03-25 08:10 UTC, egguy approved these changes

2021-03-25 08:24 UTC, merged